pipeline {
  agent any

  tools {nodejs "NodeJS-21.7.1"}

  stages {

    stage('Postman CLI Login') {
      steps {
        bat 'postman login --with-api-key PMAK-65f95816480e7100010a97ec-dd63c133bec185c4a6e753a6337d2fb9fd'
      }
    }

    stage('Running collection') {
      steps {
        bat 'newman run "https://api.getpostman.com/collections/23507450-c8154f91-92de-49d4-8007-464bdc8fea15?apikey=PMAK-65f95816480e7100010a97ec-dd63c133bec185c4a6e753a6337d2fb9fd" -e "https://api.getpostman.com/environments/23507450-d5752f0c-ecf8-420d-999b-48e7fcd7094b?apikey=PMAK-65f95816480e7100010a97ec-dd63c133bec185c4a6e753a6337d2fb9fd" -d "https://raw.githubusercontent.com/omeryttnc/KesifPlus_2024/friday/FridayProjects/src/test/resources/postmanResource/userinfo.json" -r htmlextra --reporter-htmlextra-export "target/report/newman.html"'
      }
    }
  }
}